steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/my-first-project-438701/indumathi/app:$COMMIT_SHA', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/my-first-project-438701/indumathi/app:$COMMIT_SHA']

options:
  logging: REGIONAL_USER_OWNED_BUCKET
