steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'us-central1-docker.pkg.dev/my-first-project-438701/indumathi/app:${SHORT_SHA}',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/my-first-project-438701/indumathi/app:${SHORT_SHA}'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'indumathi',
      '--image', 'us-central1-docker.pkg.dev/my-first-project-438701/indumathi/app:${SHORT_SHA}',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
